---
title: "Tellez de Ita"
author: "Rodrigo Tellez de Ita"
format: html
---

```{r}
#| warning: false
here::i_am("grades.Rproj")
library(here)
library(dplyr)
library(readr)
library(vroom)
library(tidyr)
library(ggplot2)
library(stringr)

```

# 1. Introduction

Link: https://github.com/Rodrigotdi/grades.git


## 1.1 Study organisation

### Question 1: Loading of course

```{r}
#| message: false
course <- vroom(here("courses.csv"))
```

### Question 2


```{r}
#| message: false
course_table <- course|> rename ("course name"=course)|>rename(identifier=course_id)|> rename("number of exams"=nb_grades) |> knitr::kable()
course_table
```

## 1.2 Students

### Question 3

```{r}
#| message: false
students <- vroom(here("students.csv"),
                  col_types = cols(
  id = col_integer(),
  group = col_factor(),
  birth_date = col_date(format = ""),
  sex = col_factor()
))

paste(
  "The birth_date column of the students data frame is of class",
  class(students$birth_date)
)

```

## 1.3 Grades

### Question 4


```{r}
#| message: false
grades <- read_delim(here("grades.csv"),delim=";",na="_")
```

# 2. Student population analysis

### Question 5

```{r}

ggplot(students,aes(x=group))+
  geom_bar()+
  theme_minimal()
```

### Question 6

```{r}
students |>
  ggplot(aes(x = group, fill = sex)) +
  geom_bar(position = "dodge")+
  theme_minimal()
```

### Question 7


```{r}
#| message: false
library(lubridate)

students_age <- students |>
  mutate(age = time_length(today() - birth_date, unit = "year"))
ggplot(students_age, aes(x = age)) +
  geom_histogram() +
  theme_minimal()
```



### Question 8


```{r}
students_age |>
  summarise(
    median_age = round(median(age)),
    .by = group
  ) |>
  arrange(group) |> knitr::kable()

```

### Question 9

```{r}
oldest_per_group <- students_age |>
  slice_max(age, n = 1,by = group) |>
  mutate(age = round(age)) |>
  select(group,id, sex, age) |> 
  arrange(desc(age))|>
  rename("oldest age"=age)|>
  knitr::kable()

oldest_per_group
```

# 3. Simple Grade analysis

### Question 10 


```{r}
num_grades <- grades |>
  filter(!is.na(grade)) |>
  nrow()
paste("The data set contains", num_grades, "grades.")
```


### Question 11

```{r}
grades |>
  filter(!is.na(grade)) |>
  left_join(course |> select(course_id, course), by=join_by(course_id)) |>
  filter(course == "History of the Arcane") |>
  left_join(students |> select(id, group), by=join_by(id)) |>
  summarise(avg_group = mean(grade), .by = group) |>
  ggplot(aes(x = group, y = avg_group)) +
  geom_col()+
  theme_minimal()
```


### Question 12


```{r}
grades |>
  filter(!is.na(grade)) |>
  left_join(
    course |> select(course_id, trimester), join_by(course_id)) |>
  ggplot(aes(x = factor(trimester), y = grade)) +
  geom_boxplot() +
  theme_minimal()
```


# 4. Attendance analysis

### Question 13

```{r}
grades_per_student <- grades |>
  filter(!is.na(grade)) |>
  summarise(num_grades = n(), .by = id) |>
  left_join(students |> select(id, group, sex), join_by(id)) |> 
  slice_head(n = 5) 

grades_per_student

```

```{r}
grades_per_student |>
  summarise(
    min_grades = min(num_grades),
    max_grades = max(num_grades),
    avg_grades = mean(num_grades),
    median_grades = median(num_grades)
  ) |> knitr::kable()

```

### Question 14


```{r}
grades |>
  filter(!is.na(grade)) |>
  summarise(num_grades = n(), .by = id) |> 
  left_join(students |> select(id, sex), join_by(id)) |>
  ggplot(aes(x = num_grades, fill = sex)) +
  geom_histogram(position = "dodge",bins=22) + theme_minimal()
```


### Question 15


```{r}
CNA <- grades |>
  filter(!is.na(grade)) |>
  left_join(course |> select(course_id, course),join_by(course_id)) |>
  filter(course == "Celestial Navigation and Astronomy") |>
  summarise(
    nb_grades_cna = n(),
    .by = id
  ) |>
  left_join(
    students |> select(id, group),
    join_by(id)
  ) |>
  select(id, group, nb_grades_cna)

CNA |>slice_head(n=5)
```


### Question 16

```{r}
CNA|>summarise(n_students=n(), .by=nb_grades_cna) |> ggplot(aes(x=nb_grades_cna,y=n_students))+
  geom_col()
```

### Question 17

```{r}
grades |>
  filter(!is.na(grade)) |>
  left_join(
    course |> select(course_id, course),
    join_by(course_id)
  ) |>
  filter(course == "Celestial Navigation and Astronomy") |>
  summarise(
    nb_grades_cna = n(),
    .by = id
  ) |>
  left_join(
    students |> select(id, group),
    join_by(id)
  ) |>
  ggplot(aes(x = group, y = nb_grades_cna)) +
  geom_boxplot() + theme_minimal()
```

### Question 18

```{r}

```

